qlcsv: Example fails due to stdin being consumed twice (#132)
The example previously failed with:
```
$ ./qlcsv -sql '
     select
         user_id, email, item_count * 2, yy(reg_date) > 10
     FROM stdin' < users.csv
2016/10/16 17:52:09.476160 schema.go:471: could not find table "tables"
2016/10/16 17:52:09.476644 csv.go:60: Error opening bufio.peek for csv
reader EOF
2016/10/16 17:52:09.476673 planner_select.go:180: no conn? EOF
2016/10/16 17:52:09.476695 planner_select.go:40: no source? EOF
2016/10/16 17:52:09.476709 sqldriver.go:246: return error? EOF
```

The NewCsvSource call passed in stdin which was consumed, and then the
CSV source's Open was called to open /dev/stdin, but since it had
already been consumed, it caused an EOF.